apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: shopping-basket
spec:
  selector:
    app: shopping-basket
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: shopping-basket
spec:
  selector:
    matchLabels:
      app: shopping-basket
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: shopping-basket
    spec:
      containers:
        - name: shopping-basket
          image: shopping-basket:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081