spring:
  application:
    name: shopping-basket
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/${MONGO_DB:database}?retryWrites=false
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

services:
  service: https://fakestoreapi.com

feign:
  okhttp:
    enabled: true