logging:
  level:
    org.springframework.transaction.interceptor: TRACE
spring:
  application:
    name: shopping-basket
  data:
    mongodb:
      uri: mongodb://shopping-basket-mongodb-0.shopping-basket-mongodb-headless.default.svc.cluster.local:27017/database?ReadPreference=primary
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

services:
  service: https://fakestoreapi.com

feign:
  okhttp:
    enabled: true