apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopping-basket.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "shopping-basket.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "shopping-basket.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080