apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mongo.app }}
  name: {{ .Values.mongo.service.name }}
spec:
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  selector:
    app: {{ .Values.mongo.app }}
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant