replicaCount: 1
image:
  repository: shopping-basket
  tag: 0.0.12
service:
  type: NodePort
  port: 8080
  nodeport: 30081
mongodb:
  architecture: "replicaset"
  auth:
    enabled: false
    databases[0]: database
  